name: bauxite_admin_app
description: Bauxite application.

publish_to: 'none'

version: 1.0.7+19

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  qr_code_scanner: ^1.0.1
  printing: ^5.13.1
  excel: ^4.0.3
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  open_file: ^3.3.2
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.jpg"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icon/

  fonts:
    - family: NotoSan
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
 