import 'package:get/get.dart';

class AppTranslator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "dashboard": "Dashboard",
          "contracts": "Contracts",
          "add_contracts": "Add Contracts",
          "edit_contracts": "Edit Contracts",
          "pick": "Pick",
          'car_name': 'Car name',
          'car_number': 'Car number',
          'company': 'Company',
          'note': 'Note',
          'add_car': 'Add Car',
          'username': 'Username',
          'phone': 'Phone',
          'password': 'Password',
          'new_password': 'New Password',
          'confirm_pass': 'Confirm Password',
          'role': 'Role',
          'add_user': 'Add User',
          'total': 'Total',
          'search': 'Search',
          'company_name': 'Company Name',
          'province': 'Province',
          'district': 'District',
          'village': 'Village',
          'setting': 'Setting',
          'login': 'Login',
          'delete_success': 'ລົບສຳເລັດ',
          'edit_success': 'ແກ້ໄຂສຳເລັດ',
          'add_success': 'ເພີ່ມສຳເລັດ',
          'somthing_wrong': 'something went wrong',
          'please_enter_all_fiels': 'ກະລຸນາຕື່ມຂໍ້ມູນໃຫ້ຄົບ',
        },
        "la_LA": {
          "dashboard": "ແຜງຄວບຄຸມທັງໝົດ",
          "contracts": "ຂໍ້ມູນສັນຍາ",
          "add_contracts": "ເພິ່ມສັນຍາ",
          "edit_contracts": "ແກ້ໄຂສັນຍາ",
          "pick": "ເລືອກ",
          'car_name': 'ຊື່ລົດ',
          'car_number': 'ທະບຽນລົດ',
          'company': 'ບໍລິສັດ',
          'note': 'ໝາຍເຫດ',
          'add_car': 'ເພີ່ມຂໍ້ມູນລົດ',
          'username': 'ຊື່ຜູ້ໃຊ້',
          'phone': 'ເບີໂທ',
          'password': 'ລະຫັດຜ່ານ',
          'new_password': 'ລະຫັດຜ່ານໃຫມ່',
          'confirm_pass': 'ຢືນຢັນລະຫັດຜ່ານ',
          'role': 'ສຶດໃຊ້ງານ',
          'add_user': 'ເພີ່ມຂໍ້ມູນຜູ້ໃຊ້',
          'total': 'ລວມທັງໝົດ',
          'search': 'ຄົ້ນຫາ',
          'company_name': 'ຊື່ບໍລິສັດ',
          'province': 'ແຂວງ',
          'district': 'ເມືອງ',
          'village': 'ບ້ານ',
          'setting': 'ຕັ້ງຄ່າລະບົບ',
          'login': 'ເຂົ້າສູ່ລະບົບ',
          'delete_success': 'ລົບສຳເລັດ',
          'edit_success': 'ແກ້ໄຂສຳເລັດ',
          'add_success': 'ເພີ່ມສຳເລັດ',
          'somthing_wrong': 'ມີບາງຢ່າງຜິດພາດ',
          'please_enter_all_fiels': 'ກະລຸນາຕື່ມຂໍ້ມູນໃຫ້ຄົບ',
        },
      };
}
